config/routes.rb
LandingPage::Application.routes.draw do
  get "questions/new"

  resources :questions
  resources :emails

  root to: 'questions#new'

end

app/models/email.rb
class Email < ActiveRecord::Base
	validates :email, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
    # Geokit mappable
    acts_as_mappable :lat_column_name => :latitude,
                     :lng_column_name => :longitude
        
    validates :question, presence:true
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
	
  def new
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if @email.save
	  redirect_to root_path
    else
	  render 'new'
    end
  end

  def show
    @email = Email.find(params[:id])
  end

  def index
    @emails = Email.all
  end

  private
    def email_params
      params.require(:email).permit(:email);
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def new
    @newest_questions = Question.order('created_at desc').limit(10)
    @question = Question.new
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  def create
    @question = Question.new(question_params)
    
    # Get current location information using request's IP address
    @question.ip_address = env['HTTP_X_REAL_IP'] ||= env['REMOTE_ADDR']
    loc = Geokit::Geocoders::IpGeocoder.geocode(@question.ip_address)
    if loc.success
      @question.curr_lat = loc.lat
      @question.curr_lng = loc.lng
      if @question.distance_to([loc.lat, loc.lng]) <= @question.radius
        @question.is_asking_about_curr_loc = true
      else
        @question.is_asking_about_curr_loc = false
      end
    end
    
    # Reserve geocode to get location of given lat,lng input
    res = Geokit::Geocoders::GoogleGeocoder.reverse_geocode @question.latitude.to_s + "," + @question.longitude.to_s
    @question.location = res.full_address
        
    if @question.save
	  redirect_to new_email_path
    else
	  render 'new'
    end
  end

  def show
	@question = Question.find(params[:id])
  end

  private
    def question_params
	  params.require(:question).permit(:question, :radius, :longitude, :latitude);
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <h1>Groovy</h1>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groovy</title>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
</body>
</html>

app/views/questions/new.html.erb
<h1>Ask a question</h1>
<div class="container">
      <div class="row">
        <div class="col-lg-6">
          <h2>Ask anything that's on your mind either in your current location or to people around the world. </h2>

          <div style='width: 500x;'>
            <div id="map-canvas" style='width: 500px; height: 300px;'></div>
          </div>
          </br>
          <h6>Question radius</h6>
          <div id='slider-range-max'></div>
        </br>
          <div id='panel'>

          <input id='address' type='textbox' value='Stanford, CA'>
          <input onclick='codeAddress()' type='submit' value='new location' class="btn btn-default btn-warning">
          </div>
          <%= form_for :question, url:questions_path do |f| %>
           <% if @question.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@question.errors.count, "error") %> prohibited
                this post from being saved:</h2>
              <ul>
              <% @question.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
            <% end %>
             <p>
              <%= f.label :'My Question' %><br>
              <%= f.text_area :question %>
              <%= f.text_area :radius %>
              <%= f.text_area :latitude %>
              <%= f.text_area :longitude %>
            </p>
           
            <p>
              <%= f.submit 'Ask!', class: "btn btn-large btn-primary"%>
            </p>
         <% end %>
        </div>
        <div class="col-lg-6">
        <h2> Recently asked questions</h2>
        <table class ="table table-bordered">
          <thead>
            <tr>
              <th>Question</th>
              <th>Answerable by people within</th>
            </tr>
          </thead>
        <% for question in @newest_questions %>
          <tr>
            <td>
            <%= question.question %>
          </td>
          <td>
            <%=question.radius %>
            miles of
            <%= question.location %>

          </td>
        </tr>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  </br>

app/views/questions/show.html.erb
<div class="confirmation">
<h2>Thanks!</h2>

<%= link_to 'Back', new_question_path, data: { no_turbolink: true }%>
</div>